### PR TITLE
Fix: Completions should use custom install location

### PR DESCRIPTION
**Pull request by Bryan2333**

### CODE REVIEW

**Comment by Bryan2333** [comment]
I improved the fish shell plugin, here are two points:
1. Make the completions work with the custom install location. The sdkman install location is hardcoded in the original completion file.
2.  Make the `conf.d/sdk.fish` only execution in interactive mode, which can speed up fish shell when running in login-shell mode.

**Comment by Bryan2333** [comment]
I improved the plugin, here are some points:
1. Make the completions work with the custom install location. The sdkman install location is hardcoded in the original completion file.
2. Replace the tr command with fish shell builtin command

**Comment by reitzig** [comment]
Ahoi, thanks for your contribution!

1. Seems reasonable to me. In order to protect against regressions, can you add a test that fails without your change, please?
2. Does that solve a specific issue or is it just a boyscout action? Why `-r`?

**Comment by Bryan2333** [comment]
1. I'm afraid not, because I'm not familiar with the test framework.
2. No, I just want to replace the `tr` command. And yes, it is fine to use the original one. Sorry for bringing confusion.

**Comment by reitzig** [comment]
> I'm afraid not, because I'm not familiar with the test framework.

Too bad. I had hoped you might be willing to try and copy-paste something together, if my test setup was simple enough ... oh well. It _was_ just copy past, see c68660ab8051b041309c9ba97923475218347587.

> No, I just want to replace the tr command. And yes, it is fine to use the original one. Sorry for bringing confusion.

Gotcha, no worries. I'm fine with avoiding `tr`, but I think we can drop `-r`?

**Comment by reitzig** [comment]
Couldn't figure out how to push to your PR (did you check the box to allow maintainer edits? 🤔) so I'm closing this in favor of #51. 

Thanks again!

FWIW:

> I think we can drop `-r`

I checked; no, we can't. Apparently, `string replace` only handles escapes such as `\n` properly in regex-mode. 🙄 The more you know!

**Comment by reitzig** [comment]
Released with [v2.1.0](https://github.com/reitzig/sdkman-for-fish/releases/tag/v2.1.0), thanks!

**Pull request closed without merging**
